kind: pipeline
type: docker 
name: default

steps:
  - name: build
    image: mcr.microsoft.com/dotnet/aspnet:5.0-focal
    commands:
      - dotnet restore
      - dotnet build -c Release
      - echo 项目生成成功
    